### ISSUE TITLE
tabsidebar のハイライトが :terminal の中で vim を起動すると1行だけ失われることがある

### ISSUE THREAD

**Issue by tyru** [rbtnn/vim#10]
これが仕様かどうかも分かってないですが、一応報告しておきます。
（`:redraw` すれば直るし、 `git commit` ぐらいしか terminal の中で vim を起動しないのでそんな問題とも思ってないです）

# 環境

WSL Debian
OS バージョン: Microsoft Windows 10 Pro 10.0.17134

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.5 (stretch)
Release:        9.5
Codename:       stretch
```

```
C:\Users\tyru>systeminfo | findstr /c:"OS バージョン"
OS バージョン:          10.0.17134 N/A ビルド 17134
```

# vimrc

```vim
set showtabsidebar=2
set tabsidebarcolumns=20
set norestorescreen
set t_ti=
set t_te=
```

ちなみに `set t_ti= t_te=` しなかった場合のデフォルトの値は

```
:set t_ti? t_te?
  t_ti=^[[?1049h
  t_te=^[[?1049l
```

# bash PS1

関係あるか分かりませんが PS1 の値も貼っておきます。

```
$ echo $PS1
\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\] ($?)\n\$
```

# 手順

1. `vim --clean -u vimrc`
2. `:terminal`
3. `vim --clean -u vimrc`
    * bash の中でもう一個 vim を立ち上げる
4. `:q`
    * 内側の vim をすぐ終了する
5. bash 上で一度だけエンターを押す
6. 左の tabsidebar の描画が1行だけハイライトが失われる

5 のエンターを押さなくても再現する時があって謎です。
ただ 5 をやると今のところ再現率 100% です。

# GIF

![98991c14b82609ddeb3497a64ff0e6c4](https://user-images.githubusercontent.com/48169/48298800-e0ddd900-e506-11e8-9d1f-d285f4b0cb3e.gif)

**Comment by tyru** [comment]
![image](https://user-images.githubusercontent.com/48169/48299516-1a1b4680-e511-11e8-9190-a00ca321aa23.png)

vim でなくても再現する時ありますね…（エンター押す前 (`git push` 直後) もこうなってました）
（スクショの colorscheme は [spring-night](https://github.com/rhysd/vim-color-spring-night) になってますが）

**Comment by rbtnn** [comment]
@tyru issueありがとうございます。
この問題は気が付いてはいたんですが、いまのところ修正目途がたってない感じです。
ちなみに手元のWindows環境でも発生しているのでOS依存ではないです。

**Comment by tyru** [comment]
ありがとうございます！修正確認できました！
